cargo-features = ["edition2024"]

[package]
name = "token-faucet-backend"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.3.0"
spl-token = "4.0"
borsh = "1.5.7"
thiserror = "2.0.12"